export const C = {
  bg: '#0f1117',
  surface: '#181c27',
  card: '#1e2333',
  border: '#2a3050',
  accent: '#f59e0b',
  blue: '#3b82f6',
  green: '#22c55e',
  red: '#ef4444',
  yellow: '#eab308',
  purple: '#a855f7',
  orange: '#f97316',
  teal: '#14b8a6',
  pink: '#ec4899',
  text: '#e2e8f0',
  muted: '#64748b',
  white: '#ffffff',
};

export const S = {
  app: { fontFamily: "'Inter',system-ui,sans-serif", background: C.bg, minHeight: '100vh', color: C.text, display: 'flex', flexDirection: 'row' },
  sidebar: { width: 240, background: C.surface, borderRight: `1px solid ${C.border}`, display: 'flex', flexDirection: 'column', flexShrink: 0, minHeight: '100vh', position: 'sticky', top: 0, height: '100vh', overflowY: 'auto' },
  logo: { padding: '20px 16px 14px', borderBottom: `1px solid ${C.border}`, flexShrink: 0 },
  logoText: { fontSize: 16, fontWeight: 800, color: C.white, letterSpacing: '-0.3px' },
  logoSub: { fontSize: 11, color: C.muted, marginTop: 2 },
  navGroup: { padding: '10px 16px 2px', fontSize: 10, color: C.muted, fontWeight: 700, letterSpacing: '1px', textTransform: 'uppercase', marginTop: 8 },
  navItem: (a) => ({ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 16px', cursor: 'pointer', background: a ? `${C.accent}15` : 'transparent', borderLeft: a ? `3px solid ${C.accent}` : '3px solid transparent', color: a ? C.accent : C.muted, fontSize: 13, fontWeight: a ? 600 : 400, transition: 'all .12s', userSelect: 'none' }),
  main: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, overflow: 'auto' },
  header: { padding: '16px 24px', borderBottom: `1px solid ${C.border}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: C.surface, flexShrink: 0, position: 'sticky', top: 0, zIndex: 10 },
  headerTitle: { fontSize: 18, fontWeight: 700, color: C.white },
  content: { padding: 24, flex: 1 },
  card: { background: C.card, border: `1px solid ${C.border}`, borderRadius: 10, padding: 20, marginBottom: 16 },
  g2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 },
  g3: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, marginBottom: 16 },
  g4: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: 16, marginBottom: 16 },
  stat: (c) => ({ background: C.card, border: `1px solid ${C.border}`, borderRadius: 10, padding: 18, borderTop: `3px solid ${c}` }),
  statVal: { fontSize: 26, fontWeight: 800, color: C.white, lineHeight: 1 },
  statLbl: { fontSize: 12, color: C.muted, marginTop: 5 },
  secTitle: { fontSize: 14, fontWeight: 700, color: C.white, marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8 },
  badge: (c) => ({ display: 'inline-flex', alignItems: 'center', padding: '3px 9px', borderRadius: 20, fontSize: 11, fontWeight: 600, background: `${c}22`, color: c }),
  btn: (c = C.accent) => ({ background: c, color: c === C.accent ? '#000' : C.white, border: 'none', borderRadius: 7, padding: '8px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer', transition: 'opacity .1s' }),
  btnO: { background: 'transparent', color: C.muted, border: `1px solid ${C.border}`, borderRadius: 7, padding: '7px 13px', fontSize: 12, cursor: 'pointer' },
  btnR: { background: 'transparent', color: C.red, border: `1px solid ${C.red}44`, borderRadius: 7, padding: '7px 13px', fontSize: 12, cursor: 'pointer' },
  inp: { background: '#0f1117', border: `1px solid ${C.border}`, borderRadius: 7, padding: '8px 12px', fontSize: 13, color: C.text, width: '100%', boxSizing: 'border-box', outline: 'none' },
  sel: { background: '#0f1117', border: `1px solid ${C.border}`, borderRadius: 7, padding: '8px 12px', fontSize: 13, color: C.text, width: '100%', boxSizing: 'border-box', outline: 'none' },
  lbl: { fontSize: 12, color: C.muted, marginBottom: 5, display: 'block' },
  fg: { marginBottom: 14 },
  modal: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,.78)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  mbox: { background: C.card, border: `1px solid ${C.border}`, borderRadius: 12, padding: 28, width: 560, maxHeight: '90vh', overflowY: 'auto' },
  tbl: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: '9px 12px', borderBottom: `1px solid ${C.border}`, color: C.muted, fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.4px' },
  td: { padding: '9px 12px', borderBottom: `1px solid ${C.border}22`, color: C.text, verticalAlign: 'middle' },
  alert: (c) => ({ background: `${c}15`, border: `1px solid ${c}40`, borderRadius: 8, padding: '9px 13px', marginBottom: 10, fontSize: 13, color: c, display: 'flex', alignItems: 'center', gap: 8 }),
  ta: { background: '#0f1117', border: `1px solid ${C.border}`, borderRadius: 7, padding: '8px 12px', fontSize: 13, color: C.text, width: '100%', boxSizing: 'border-box', outline: 'none', resize: 'vertical', minHeight: 70 },
};
